In [1]:
import pandas as pd
import numpy as np
import config
from sqlalchemy import text
import datetime
import random
print(config.version)
print(config.connection_string)
pd.set_option('display.max_columns', None)
pd.options.mode.copy_on_write = True

3.2.25.Dev
postgresql://postgres:sa@localhost/icip

In [2]:
def get_ps(year, specialite):
    sql=f"""
select ps.id, ps.nom, ps.prenom, an.dept_id, an.id adresse_norm_id, i.id iris, an.lon, an.lat, 'L' code_mode_exercice  from ps
join tarif t on t.ps_id = ps.id
join tarif_date_source tds on tds.tarif_id=t.id
join cabinet c on t.cabinet_id=c.id
join adresse_raw ar on c.adresse_raw_id=ar.id
join adresse_norm an on ar.adresse_norm_id=an.id
join specialite_profession sp on sp.profession_id=t.profession_id
join specialite s on s.id=sp.specialite_id
join iris.iris i on i.code=an.iris
where sp.specialite_id={specialite}
and tds.date_source_id >= {year}00 and  tds.date_source_id < {year+1}00
group by ps.id, c.id, an.id, i.id
"""
    print(f"Quering PS for year {year} and specialite {specialite}")
    return pd.read_sql(sql, config.connection_string)

In [3]:
def get_pa(year, specialite, is_medecin):
    if is_medecin:
        sql = f"""
select pa.id, pa.inpp, pa.nom, pa.prenom, an.dept_id, an.id adresse_norm_id, i.id iris, an.lon, an.lat, ps.code_mode_exercice 
from apl.ps_libreacces ps
join personne_activite pa on pa.inpp=ps.inpp
join pa_adresse_norm_date_source pands on pands.personne_activite_id=pa.id and pands.date_source_id=ps.date_source_id
join personne_activite_diplome pad on pad.personne_activite_id=pa.id
join diplome d on d.code_diplome=ps.code_diplome
join profession_diplome pd on pd.diplome_id=d.id
join profession p on p.id=pd.profession_id
join specialite_profession sp on sp.profession_id=p.id
join adresse_norm an on an.id=pands.adresse_norm_id
join date_source ds on ds.id=pands.date_source_id
join iris.iris i on i.code=an.iris
where sp.specialite_id={specialite}
--and ps.code_mode_exercice='L'
and ds.annee={year}
and pands.adresse_norm_id is not null
group by pa.id, an.id, i.id, ps.code_mode_exercice
"""
    else:
        sql = f"""
select pa.id, pa.inpp, pa.nom, pa.prenom, an.dept_id, an.id adresse_norm_id, i.id iris, an.lon, an.lat, ps.code_mode_exercice
from apl.ps_libreacces ps
join personne_activite pa on pa.inpp=ps.inpp
join pa_adresse_norm_date_source pands on pands.personne_activite_id=pa.id and pands.date_source_id=ps.date_source_id
join profession_code_profession pcp on pcp.code_profession_id=ps.code_profession
join specialite_profession sp on sp.profession_id=pcp.profession_id
join adresse_norm an on an.id=pands.adresse_norm_id
join date_source ds on ds.id=pands.date_source_id
join iris.iris i on i.code=an.iris
where sp.specialite_id={specialite}
--and ps.code_mode_exercice='L'
and ds.annee={year}
and pands.adresse_norm_id is not null
group by pa.id, an.id, i.id, ps.code_mode_exercice
"""    
    print(f"Quering PA for year {year} and specialite {specialite} for is_medecin={is_medecin}")
    print(sql)
    return pd.read_sql(sql, config.connection_string)

In [4]:
def get_by_source(year, specialite, source):
    if source=="PS":
        return get_ps(year, specialite)
    elif source=="PA":
        return get_pa(year, specialite, specialite<21)
    else:
        raise ValueError(f"Bad source: {source}")

In [5]:
def get_pop_iris(year):
    yy=min(21, year)
    sql = f"""
select i.id iris, pi.iris iris_string, c.code code_commune, i.type type_iris, pi.pop, pi.pop0002, pi.pop0305, pi.pop0610, pi.pop1117, pi.pop1824, pi.pop2539, pi.pop4054, pi.pop5564, pi.pop6579, pi.pop80p
from iris.pop_iris pi
join iris.iris i on  pi.iris=i.code
join iris.commune c on i.commune_id=c.id
where year={yy}
"""
    print(sql)
    return pd.read_sql(text(sql), config.connection_string)

In [6]:
def get_iris_matrix(time: int, time_type: str):
    sql = f"""
(select iris.id "iris1", iris.id "iris2", 0 "km", 0 "time_hc", 0 "time_hp" from iris.iris
union
select iris_id_from as "iris1", iris_id_to "iris2", route_km "km", route_min "time_hc", route_hp_min "time_hp" from iris.iris_matrix
where route_min <= {time}) order by "iris1", "iris2"
"""
    print(sql)
    m = pd.read_sql(sql, config.connection_string)
    m["time"] = m[f"time_{time_type.lower()}"].copy()
    return m

In [7]:
specialite=10
year=21
source="PA"
time=30
time_type="HC"
# accessibilite_exp=-0.12 #0.08 pour 45
accessibilite_exp=-0.12
print(year, specialite, source, time, time_type, accessibilite_exp)
debug=61210000
writer = pd.ExcelWriter(f"out/debug_{debug}_{year}_{specialite}_{time}.xlsx")

21 10 PA 30 HC -0.12

In [8]:
# Very long
iris_matrix = get_iris_matrix(time, time_type)
iris_matrix["iris"] = iris_matrix["iris2"].astype("int64")
iris_matrix

(select iris.id "iris1", iris.id "iris2", 0 "km", 0 "time_hc", 0 "time_hp" from iris.iris
union
select iris_id_from as "iris1", iris_id_to "iris2", route_km "km", route_min "time_hc", route_hp_min "time_hp" from iris.iris_matrix
where route_min <= 30) order by "iris1", "iris2"

             iris1       iris2  km  time_hc  time_hp  time        iris
0         10010000    10010000   0        0        0     0    10010000
1         10010000    10280000   8        9       10     9    10280000
2         10010000    11880000   6        7        8     7    11880000
3         10010000    13510000   7        8        9     8    13510000
4         10020000    10020000   0        0        0     0    10020000
...            ...         ...  ..      ...      ...   ...         ...
771469  2023640000  2022920000  11       26       26    26  2022920000
771470  2023640000  2023640000   0        0        0     0  2023640000
771471  2023650000  2021350000   6        8        9     8  2021350000
771472  2023650000  2023650000   0        0        0     0  2023650000
771473  2023660000  2023660000   0        0        0     0  2023660000

[771474 rows x 7 columns]

In [9]:
pop_iris = get_pop_iris(year)
pop_iris

select i.id iris, pi.iris iris_string, c.code code_commune, i.type type_iris, pi.pop, pi.pop0002, pi.pop0305, pi.pop0610, pi.pop1117, pi.pop1824, pi.pop2539, pi.pop4054, pi.pop5564, pi.pop6579, pi.pop80p
from iris.pop_iris pi
join iris.iris i on  pi.iris=i.code
join iris.commune c on i.commune_id=c.id
where year=21

,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p
0,811540000,811540000,81154,C,80.000000,2.105263,3.157895,5.263158,4.210526,2.105263,4.210526,17.894737,17.894737,16.842105,6.315789
1,840060000,840060000,84006,C,71.000000,2.028571,3.042857,9.128571,3.042857,2.028571,16.228571,12.171429,9.128571,6.085714,8.114286
2,831370505,831370505,83137,A,2415.603495,41.186112,48.275467,94.134615,115.121536,326.658259,533.315278,434.083692,312.409335,366.371556,144.047644
3,841310000,841310000,84131,C,1957.000000,49.149297,42.460084,114.795089,155.684666,87.600180,241.124946,415.875456,308.979751,375.917834,165.412698
4,830230301,830230301,83023,A,6065.912226,272.510569,207.163033,361.858727,505.651248,304.890171,1062.904509,1134.710813,858.705751,1071.984602,285.532804
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48550,885050000,885050000,88505,C,122.000000,2.085470,5.213675,8.341880,8.341880,4.170940,19.811966,31.282051,20.854701,16.683761,5.213675
48551,912280114,912280114,91228,A,2571.910873,102.489408,126.078212,199.645438,182.694426,223.818783,582.214370,531.534442,240.058416,227.986361,155.391015
48552,920460108,920460108,92046,A,2080.941456,69.990100,97.857434,99.464274,177.378541,212.024683,517.750823,398.113906,255.524935,186.343973,66.492788
48553,940460202,940460202,94046,A,2435.011871,90.000439,77.000375,125.000609,198.000965,427.002082,680.003315,670.003266,145.000707,17.000083,6.000029
48554,940540104,940540104,94054,A,2212.488970,125.035512,106.898912,177.768543,183.023675,235.085841,520.735553,433.105553,245.609771,141.758801,43.466809

In [10]:
pop_iris[pop_iris["iris"]==debug].to_excel(writer, sheet_name="iris", index=None)
pop_iris[pop_iris["iris"]==debug]

,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p
18984,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916

In [11]:
ps_df = get_by_source(year, specialite, source)
ps_df

Quering PA for year 21 and specialite 10 for is_medecin=True

select pa.id, pa.inpp, pa.nom, pa.prenom, an.dept_id, an.id adresse_norm_id, i.id iris, an.lon, an.lat, ps.code_mode_exercice
from apl.ps_libreacces ps
join personne_activite pa on pa.inpp=ps.inpp
join pa_adresse_norm_date_source pands on pands.personne_activite_id=pa.id and pands.date_source_id=ps.date_source_id
join personne_activite_diplome pad on pad.personne_activite_id=pa.id
join diplome d on d.code_diplome=ps.code_diplome
join profession_diplome pd on pd.diplome_id=d.id
join profession p on p.id=pd.profession_id
join specialite_profession sp on sp.profession_id=p.id
join adresse_norm an on an.id=pands.adresse_norm_id
join date_source ds on ds.id=pands.date_source_id
join iris.iris i on i.code=an.iris
where sp.specialite_id=10
--and ps.code_mode_exercice='L'
and ds.annee=21
and pands.adresse_norm_id is not null
group by pa.id, an.id, i.id, ps.code_mode_exercice

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice]
Index: []

In [12]:
ps_df[ps_df["iris"]==debug].to_excel(writer, sheet_name="ps", index=None)
ps_df[ps_df["iris"]==debug]

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice]
Index: []

In [13]:
nb_ps = ps_df["id"].nunique()
nb_cabinet_ps = ps_df.groupby(["id", "lon", "lat"])
print(f"Nb unique PS {nb_ps}")
print(f"Nb cabinet {len(nb_cabinet_ps)}")

Nb unique PS 0
Nb cabinet 0

In [14]:
ps_df["key"] = ps_df["id"].astype(str) + "_" + ps_df["code_mode_exercice"] + "_" + ps_df["lat"].astype(str) + "_" + ps_df["lon"].astype(str)
ps_df["nb_cabinet"] = ps_df.groupby("id")["key"].transform("nunique")
ps_df["nb_cabinet"].value_counts(normalize=True)

Series([], Name: proportion, dtype: float64)

In [15]:
ps_df[ps_df["iris"]==debug].to_excel(writer, sheet_name="nb_cabinet", index=None)
ps_df[ps_df["iris"]==debug]

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice, key, nb_cabinet]
Index: []

In [16]:
ps_df = ps_df[ps_df["code_mode_exercice"]=="L"]
ps_df["weight"] = 1 / ps_df["nb_cabinet"]
ps_df["nb"] = ps_df.groupby("iris")["weight"].transform("sum")
ps_df.head(10)
# 0.5 2.17
# 0.5 8.83

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice, key, nb_cabinet, weight, nb]
Index: []

In [17]:
ps_df[ps_df["iris"]==debug].to_excel(writer, sheet_name="nb", index=None)
ps_df[ps_df["iris"]==debug]

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice, key, nb_cabinet, weight, nb]
Index: []

In [18]:
ps_df = ps_df.sort_values(by='iris')
ps_df2 = ps_df.drop_duplicates(subset=['iris', 'nb'])
ps_df2

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice, key, nb_cabinet, weight, nb]
Index: []

In [19]:
ps_df2[ps_df2["iris"]==debug].to_excel(writer, sheet_name="drop", index=None)
ps_df2[ps_df2["iris"]==debug]

Empty DataFrame
Columns: [id, inpp, nom, prenom, dept_id, adresse_norm_id, iris, lon, lat, code_mode_exercice, key, nb_cabinet, weight, nb]
Index: []

In [20]:
iris_matrix_pop_df = iris_matrix.merge(pop_iris, on="iris", how="left", suffixes=('', '')) #iris = iris2
iris_matrix_pop_df

,iris1,iris2,km,time_hc,time_hp,time,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p
0,10010000,10010000,0,0,0,0,10010000,010010000,01001,C,832.0,32.222177,27.437983,54.841845,79.169950,29.129798,146.720566,171.578985,125.962948,122.797689,42.138058
1,10010000,10280000,8,9,10,9,10280000,010280000,01028,C,621.0,22.723364,29.574898,53.956390,70.586718,22.773615,107.898596,115.308426,89.365644,83.584630,25.227720
2,10010000,11880000,6,7,8,7,11880000,011880000,01188,C,689.0,27.464907,32.744372,56.307877,80.854142,33.549841,121.822112,161.009834,80.861738,67.564798,26.820380
3,10010000,13510000,7,8,9,8,13510000,013510000,01351,C,1613.0,75.662640,71.994413,121.933338,168.504238,95.207879,317.353521,325.511955,192.066782,182.771975,61.993259
4,10020000,10020000,0,0,0,0,10020000,010020000,01002,C,267.0,5.987773,12.067776,19.066467,34.050318,11.243816,40.450221,72.596915,24.614834,29.997951,16.923930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771469,2023640000,2022920000,11,26,26,26,2022920000,2B2920000,2B292,C,61.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.089286,14.160714,26.142857,19.607143
771470,2023640000,2023640000,0,0,0,0,2023640000,2B3640000,2B364,C,36.0,0.000000,0.000000,0.000000,0.000000,1.000000,4.000000,4.000000,10.000000,11.000000,6.000000
771471,2023650000,2021350000,6,8,9,8,2021350000,2B1350000,2B135,C,324.0,3.980971,2.049514,2.049514,2.020847,18.774109,42.392738,42.077099,55.572529,98.952018,56.130660
771472,2023650000,2023650000,0,0,0,0,2023650000,2B3650000,2B365,C,100.0,0.000000,0.943396,0.000000,3.773585,9.433962,9.433962,9.433962,23.584906,29.245283,14.150943
771473,2023660000,2023660000,0,0,0,0,2023660000,2B3660000,2B366,C,108.0,1.080000,1.080000,2.160000,1.080000,1.080000,15.120000,10.800000,24.840000,32.400000,18.360000

In [21]:
iris_matrix_pop_df[iris_matrix_pop_df["iris2"]==debug].to_excel(writer, sheet_name="iris_matrix", index=None)
iris_matrix_pop_df[iris_matrix_pop_df["iris2"]==debug]

,iris1,iris2,km,time_hc,time_hp,time,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p
9550,60590000,61210000,11,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10113,60880102,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10471,60880507,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10485,60880508,61210000,8,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10499,60880509,61210000,8,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10509,60880601,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10519,60880602,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10531,60880603,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10541,60880604,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
10563,60880701,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11253,60881601,61210000,8,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11266,60881602,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11278,60881603,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11292,60881604,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11336,60881701,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11353,60881702,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11367,60881703,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11383,60881704,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11399,60881705,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11663,60882201,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11679,60882202,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
11696,60882203,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916
13144,61210000,61210000,0,0,0,0,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916

In [22]:
accessibilite_fn = lambda x: np.exp(accessibilite_exp * x)
iris_matrix_pop_df["accessibilite_weight"] = accessibilite_fn(iris_matrix_pop_df["time"])
iris_matrix_pop_df.head(10)

,iris1,iris2,km,time_hc,time_hp,time,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p,accessibilite_weight
0,10010000,10010000,0,0,0,0,10010000,010010000,01001,C,832.000000,32.222177,27.437983,54.841845,79.169950,29.129798,146.720566,171.578985,125.962948,122.797689,42.138058,1.000000
1,10010000,10280000,8,9,10,9,10280000,010280000,01028,C,621.000000,22.723364,29.574898,53.956390,70.586718,22.773615,107.898596,115.308426,89.365644,83.584630,25.227720,0.339596
2,10010000,11880000,6,7,8,7,11880000,011880000,01188,C,689.000000,27.464907,32.744372,56.307877,80.854142,33.549841,121.822112,161.009834,80.861738,67.564798,26.820380,0.431711
3,10010000,13510000,7,8,9,8,13510000,013510000,01351,C,1613.000000,75.662640,71.994413,121.933338,168.504238,95.207879,317.353521,325.511955,192.066782,182.771975,61.993259,0.382893
4,10020000,10020000,0,0,0,0,10020000,010020000,01002,C,267.000000,5.987773,12.067776,19.066467,34.050318,11.243816,40.450221,72.596915,24.614834,29.997951,16.923930,1.000000
5,10020000,10070000,8,10,11,10,10070000,010070000,01007,C,2833.000000,115.373022,110.854636,219.371714,278.178983,142.521978,590.944118,557.885647,344.697811,360.231255,112.940835,0.301194
6,10020000,11490000,10,13,14,13,11490000,011490000,01149,C,1094.000000,33.800846,37.708867,65.449467,130.271127,56.032249,166.728750,247.820554,162.864409,162.080298,31.243433,0.210136
7,10020000,11990000,6,7,8,7,11990000,011990000,01199,C,2124.000000,76.627024,63.592945,135.754441,239.865643,129.199625,367.439586,438.473150,258.163675,263.845355,151.038556,0.431711
8,10040101,10040101,0,0,0,0,10040101,010040101,01004,A,1796.951774,77.519678,43.974406,98.916060,122.511553,349.080836,418.089799,239.636958,144.751947,200.290026,102.180511,1.000000
9,10040102,10040102,0,0,0,0,10040102,010040102,01004,A,3837.421806,148.643017,157.192812,250.217020,321.725625,386.552428,736.930320,707.168200,434.715456,488.393411,205.883519,1.000000

In [23]:
iris_matrix_pop_df[iris_matrix_pop_df["iris2"]==debug].to_excel(writer, sheet_name="accessibilite", index=None)
iris_matrix_pop_df[iris_matrix_pop_df["iris2"]==debug]

,iris1,iris2,km,time_hc,time_hp,time,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p,accessibilite_weight
9550,60590000,61210000,11,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.165299
10113,60880102,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
10471,60880507,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
10485,60880508,61210000,8,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
10499,60880509,61210000,8,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
10509,60880601,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
10519,60880602,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
10531,60880603,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.165299
10541,60880604,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.165299
10563,60880701,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.165299
11253,60881601,61210000,8,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
11266,60881602,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
11278,60881603,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
11292,60881604,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.165299
11336,60881701,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
11353,60881702,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
11367,60881703,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
11383,60881704,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
11399,60881705,61210000,8,13,19,13,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.210136
11663,60882201,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
11679,60882202,61210000,9,15,22,15,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.165299
11696,60882203,61210000,9,14,20,14,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,0.186374
13144,61210000,61210000,0,0,0,0,61210000,061210000,06121,C,1471.0,26.88639,31.534309,55.567568,79.991458,83.865916,206.509731,307.039686,243.487553,300.013473,136.103916,1.000000

In [24]:
cols = [col for col in iris_matrix_pop_df.columns if "pop" in col and col != "pop"]
cols

['pop0002',
 'pop0305',
 'pop0610',
 'pop1117',
 'pop1824',
 'pop2539',
 'pop4054',
 'pop5564',
 'pop6579',
 'pop80p']

In [25]:
def get_over(year, specialite, is_medecin):
    yy=min(year, 24)
    if is_medecin:
        sql = f"""select o.* from apl.overrepresentation o
        join specialite s on s.psp_spe_snds=o.psp_spe_snds
        where o.year={yy}
        and s.id={specialite}
        """
    else:
        sql = f"""select o.* from apl.overrepresentation o
        join specialite s on s.psp_act_snds=o.psp_act_snds
        where o.year={yy}
        and s.id={specialite}
        """
    over = pd.read_sql(sql, config.connection_string)
    return over

over = get_over(year, specialite, specialite<21)
over

,year,psp_spe_snds,p0002,p0305,p0610,p1117,p1824,p2539,p4054,p5564,p6579,p80p
0,21,1,1.166949,0.539683,0.402415,0.420643,0.708842,0.929717,0.886061,1.074038,1.491386,2.405645

In [26]:
over.to_excel(writer, sheet_name="over", index=None)

In [27]:
if len(over) > 0:
    weights = over.values[0,3:]
else:
    weights = np.ones(len(over.columns) - 3)
weights

array([0.53968312, 0.40241483, 0.42064349, 0.70884153, 0.92971694,
       0.88606123, 1.07403771, 1.49138583, 2.40564513])

In [28]:
iris_matrix_pop_df["pop_gp"] = sum(w * iris_matrix_pop_df[c] for w, c in zip(weights, cols))
if specialite == 5: # todo ajouter sage femme
    iris_matrix_pop_df["pop_gp"] /= 2
iris_matrix_pop_df=iris_matrix_pop_df.sort_values(by='iris2')
iris_matrix_pop_df.head(5)

,iris1,iris2,km,time_hc,time_hp,time,iris,iris_string,code_commune,type_iris,pop,pop0002,pop0305,pop0610,pop1117,pop1824,pop2539,pop4054,pop5564,pop6579,pop80p,accessibilite_weight,pop_gp
0,10010000,10010000,0,0,0,0,10010000,010010000,01001,C,832.0,32.222177,27.437983,54.841845,79.169950,29.129798,146.720566,171.578985,125.962948,122.797689,42.138058,1.000000,932.254221
100,10280000,10010000,8,9,10,9,10010000,010010000,01001,C,832.0,32.222177,27.437983,54.841845,79.169950,29.129798,146.720566,171.578985,125.962948,122.797689,42.138058,0.339596,932.254221
725,11880000,10010000,6,7,8,7,10010000,010010000,01001,C,832.0,32.222177,27.437983,54.841845,79.169950,29.129798,146.720566,171.578985,125.962948,122.797689,42.138058,0.431711,932.254221
1368,13510000,10010000,7,8,9,8,10010000,010010000,01001,C,832.0,32.222177,27.437983,54.841845,79.169950,29.129798,146.720566,171.578985,125.962948,122.797689,42.138058,0.382893,932.254221
578,11490000,10020000,10,13,14,13,10020000,010020000,01002,C,267.0,5.987773,12.067776,19.066467,34.050318,11.243816,40.450221,72.596915,24.614834,29.997951,16.923930,0.210136,273.385619

In [29]:
ratio_mean=1
if specialite!=5:
    test_pop=iris_matrix_pop_df.drop_duplicates(subset=['iris2'])
    ratio=test_pop["pop_gp"]/(test_pop["pop"]+1)
    ratio_mean=np.mean(ratio)
    print(ratio_mean)
    iris_matrix_pop_df["pop_gp"]=iris_matrix_pop_df["pop_gp"]/ratio_mean

1.1245622926622794

In [30]:
matrix_df = iris_matrix_pop_df[["iris1","iris2","km","time","accessibilite_weight","pop_gp","pop","type_iris"]]
matrix_df.head(5)

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris
0,10010000,10010000,0,0,1.000000,828.992958,832.0,C
100,10280000,10010000,8,9,0.339596,828.992958,832.0,C
725,11880000,10010000,6,7,0.431711,828.992958,832.0,C
1368,13510000,10010000,7,8,0.382893,828.992958,832.0,C
578,11490000,10020000,10,13,0.210136,243.104024,267.0,C

In [31]:
matrix_df[matrix_df["iris2"]==debug].to_excel(writer, sheet_name=f"pop_ajustee_{ratio_mean:.3f}", index=None)
matrix_df[matrix_df["iris2"]==debug]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris
11663,60882201,61210000,9,14,0.186374,1585.38063,1471.0,C
10531,60880603,61210000,9,15,0.165299,1585.38063,1471.0,C
11679,60882202,61210000,9,15,0.165299,1585.38063,1471.0,C
11336,60881701,61210000,8,13,0.210136,1585.38063,1471.0,C
11353,60881702,61210000,8,13,0.210136,1585.38063,1471.0,C
13144,61210000,61210000,0,0,1.000000,1585.38063,1471.0,C
11367,60881703,61210000,9,14,0.186374,1585.38063,1471.0,C
10485,60880508,61210000,8,14,0.186374,1585.38063,1471.0,C
10563,60880701,61210000,9,15,0.165299,1585.38063,1471.0,C
11383,60881704,61210000,8,13,0.210136,1585.38063,1471.0,C
10471,60880507,61210000,8,13,0.210136,1585.38063,1471.0,C
10499,60880509,61210000,8,14,0.186374,1585.38063,1471.0,C
11278,60881603,61210000,9,14,0.186374,1585.38063,1471.0,C
11253,60881601,61210000,8,14,0.186374,1585.38063,1471.0,C
11266,60881602,61210000,8,13,0.210136,1585.38063,1471.0,C
11696,60882203,61210000,9,14,0.186374,1585.38063,1471.0,C
10541,60880604,61210000,9,15,0.165299,1585.38063,1471.0,C
10519,60880602,61210000,9,14,0.186374,1585.38063,1471.0,C
11292,60881604,61210000,9,15,0.165299,1585.38063,1471.0,C
10113,60880102,61210000,8,13,0.210136,1585.38063,1471.0,C
11399,60881705,61210000,8,13,0.210136,1585.38063,1471.0,C
10509,60880601,61210000,8,13,0.210136,1585.38063,1471.0,C
9550,60590000,61210000,11,15,0.165299,1585.38063,1471.0,C

In [32]:
matrix_df["iris"] = matrix_df["iris1"].copy()
matrix_df = matrix_df.sort_values(by='iris2')
matrix_merge_df = matrix_df.merge(ps_df2, on="iris", how="left", suffixes=('', ''))
matrix_merge_df

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb
0,10010000,10010000,0,0,1.000000,828.992958,832.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10280000,10010000,8,9,0.339596,828.992958,832.0,C,10280000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11880000,10010000,6,7,0.431711,828.992958,832.0,C,11880000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13510000,10010000,7,8,0.382893,828.992958,832.0,C,13510000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11490000,10020000,10,13,0.210136,243.104024,267.0,C,11490000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771469,2023640000,2023640000,0,0,1.000000,44.591632,36.0,C,2023640000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771470,2022920000,2023640000,11,26,0.044157,44.591632,36.0,C,2022920000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771471,2021350000,2023650000,6,8,0.382893,120.798014,100.0,C,2021350000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771472,2023650000,2023650000,0,0,1.000000,120.798014,100.0,C,2023650000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
771473,2023660000,2023660000,0,0,1.000000,127.766580,108.0,C,2023660000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
matrix_merge_df[(matrix_merge_df["iris"]==debug) | (matrix_merge_df["iris"]==debug)].to_excel(writer, sheet_name=f"join_iris", index=None)
matrix_merge_df[(matrix_merge_df["iris"]==debug) | (matrix_merge_df["iris"]==debug)]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb
9552,61210000,60590000,11,15,0.165299,2346.881002,2189.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10097,61210000,60880102,10,15,0.165299,1217.618689,1302.167160,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10462,61210000,60880507,8,13,0.210136,3150.060094,3258.794977,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10480,61210000,60880508,8,13,0.210136,2061.962146,2244.635592,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10499,61210000,60880509,8,14,0.186374,1601.504024,1758.198046,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10508,61210000,60880601,9,15,0.165299,3211.497847,3400.367778,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10521,61210000,60880602,9,14,0.186374,1515.075064,1564.628064,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10527,61210000,60880603,9,15,0.165299,2825.496170,2969.126397,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10536,61210000,60880604,9,15,0.165299,2503.716717,2776.024755,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10558,61210000,60880701,9,15,0.165299,2269.280377,2561.518621,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11248,61210000,60881601,9,14,0.186374,2087.063833,1963.668952,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11267,61210000,60881602,8,13,0.210136,2328.682642,2547.100345,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11269,61210000,60881603,9,15,0.165299,3267.105880,3334.828060,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11292,61210000,60881604,10,14,0.186374,3055.721245,2834.758352,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11319,61210000,60881701,9,13,0.210136,1641.948044,1708.308379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11340,61210000,60881702,9,13,0.210136,2095.417964,2060.393857,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11364,61210000,60881703,9,14,0.186374,1747.351193,1910.086974,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11376,61210000,60881704,9,14,0.186374,2155.294152,2157.701379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11401,61210000,60881705,9,13,0.210136,1888.443911,1878.223143,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11654,61210000,60882201,9,14,0.186374,1252.415053,1186.085985,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11667,61210000,60882202,9,14,0.186374,2226.745086,2234.919326,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11697,61210000,60882203,9,13,0.210136,2566.688522,2519.082764,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13140,61210000,61210000,0,0,1.000000,1585.380630,1471.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
matrix_merge_df["nb"] = matrix_merge_df["nb"].fillna(0)
matrix_merge_df = matrix_merge_df.sort_values(by=['iris1', "iris2"])
matrix_merge_df["nb"].nunique()

1

In [35]:
matrix_merge_df[(matrix_merge_df["iris"]==debug) | (matrix_merge_df["iris"]==debug)].to_excel(writer, sheet_name=f"nb", index=None)
matrix_merge_df[(matrix_merge_df["iris"]==debug) | (matrix_merge_df["iris"]==debug)]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb
9552,61210000,60590000,11,15,0.165299,2346.881002,2189.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10097,61210000,60880102,10,15,0.165299,1217.618689,1302.167160,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10462,61210000,60880507,8,13,0.210136,3150.060094,3258.794977,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10480,61210000,60880508,8,13,0.210136,2061.962146,2244.635592,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10499,61210000,60880509,8,14,0.186374,1601.504024,1758.198046,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10508,61210000,60880601,9,15,0.165299,3211.497847,3400.367778,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10521,61210000,60880602,9,14,0.186374,1515.075064,1564.628064,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10527,61210000,60880603,9,15,0.165299,2825.496170,2969.126397,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10536,61210000,60880604,9,15,0.165299,2503.716717,2776.024755,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
10558,61210000,60880701,9,15,0.165299,2269.280377,2561.518621,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11248,61210000,60881601,9,14,0.186374,2087.063833,1963.668952,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11267,61210000,60881602,8,13,0.210136,2328.682642,2547.100345,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11269,61210000,60881603,9,15,0.165299,3267.105880,3334.828060,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11292,61210000,60881604,10,14,0.186374,3055.721245,2834.758352,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11319,61210000,60881701,9,13,0.210136,1641.948044,1708.308379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11340,61210000,60881702,9,13,0.210136,2095.417964,2060.393857,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11364,61210000,60881703,9,14,0.186374,1747.351193,1910.086974,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11376,61210000,60881704,9,14,0.186374,2155.294152,2157.701379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11401,61210000,60881705,9,13,0.210136,1888.443911,1878.223143,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11654,61210000,60882201,9,14,0.186374,1252.415053,1186.085985,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11667,61210000,60882202,9,14,0.186374,2226.745086,2234.919326,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11697,61210000,60882203,9,13,0.210136,2566.688522,2519.082764,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
13140,61210000,61210000,0,0,1.000000,1585.380630,1471.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [36]:
# matrix_merge_df = matrix_merge_df.sort_values(by='iris1')
matrix_merge_df["wpop"] = matrix_merge_df["accessibilite_weight"] * matrix_merge_df["pop_gp"]
matrix_merge_df["swpop"] = matrix_merge_df.groupby("iris1")["wpop"].transform("sum")
matrix_merge_df["R"] = matrix_merge_df["nb"] / (matrix_merge_df["swpop"] / 100000)
matrix_merge_df.head(5)
# apl["R"].unique()

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R
0,10010000,10010000,0,0,1.000000,828.992958,832.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,828.992958,1876.269522,0.0
103,10010000,10280000,8,9,0.339596,597.452882,621.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,202.892326,1876.269522,0.0
727,10010000,11880000,6,7,0.431711,626.194568,689.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,270.334785,1876.269522,0.0
1369,10010000,13510000,7,8,0.382893,1499.242934,1613.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,574.049454,1876.269522,0.0
5,10020000,10020000,0,0,1.000000,243.104024,267.0,C,10020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,243.104024,2145.470352,0.0

In [37]:
matrix_merge_df[(matrix_merge_df["iris"]==debug) | (matrix_merge_df["iris"]==debug)].to_excel(writer, sheet_name=f"R", index=None)
matrix_merge_df[(matrix_merge_df["iris"]==debug) | (matrix_merge_df["iris"]==debug)]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R
9552,61210000,60590000,11,15,0.165299,2346.881002,2189.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,387.936820,10722.737459,0.0
10097,61210000,60880102,10,15,0.165299,1217.618689,1302.167160,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,201.271016,10722.737459,0.0
10462,61210000,60880507,8,13,0.210136,3150.060094,3258.794977,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,661.941252,10722.737459,0.0
10480,61210000,60880508,8,13,0.210136,2061.962146,2244.635592,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,433.292624,10722.737459,0.0
10499,61210000,60880509,8,14,0.186374,1601.504024,1758.198046,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,298.478673,10722.737459,0.0
10508,61210000,60880601,9,15,0.165299,3211.497847,3400.367778,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,530.857024,10722.737459,0.0
10521,61210000,60880602,9,14,0.186374,1515.075064,1564.628064,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,282.370564,10722.737459,0.0
10527,61210000,60880603,9,15,0.165299,2825.496170,2969.126397,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,467.051376,10722.737459,0.0
10536,61210000,60880604,9,15,0.165299,2503.716717,2776.024755,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,413.861590,10722.737459,0.0
10558,61210000,60880701,9,15,0.165299,2269.280377,2561.518621,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,375.109523,10722.737459,0.0
11248,61210000,60881601,9,14,0.186374,2087.063833,1963.668952,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,388.974385,10722.737459,0.0
11267,61210000,60881602,8,13,0.210136,2328.682642,2547.100345,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,489.340222,10722.737459,0.0
11269,61210000,60881603,9,15,0.165299,3267.105880,3334.828060,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,540.048970,10722.737459,0.0
11292,61210000,60881604,10,14,0.186374,3055.721245,2834.758352,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,569.506918,10722.737459,0.0
11319,61210000,60881701,9,13,0.210136,1641.948044,1708.308379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,345.032511,10722.737459,0.0
11340,61210000,60881702,9,13,0.210136,2095.417964,2060.393857,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,440.322898,10722.737459,0.0
11364,61210000,60881703,9,14,0.186374,1747.351193,1910.086974,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,325.660789,10722.737459,0.0
11376,61210000,60881704,9,14,0.186374,2155.294152,2157.701379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,401.690741,10722.737459,0.0
11401,61210000,60881705,9,13,0.210136,1888.443911,1878.223143,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,396.830184,10722.737459,0.0
11654,61210000,60882201,9,14,0.186374,1252.415053,1186.085985,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,233.417573,10722.737459,0.0
11667,61210000,60882202,9,14,0.186374,2226.745086,2234.919326,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,415.007335,10722.737459,0.0
11697,61210000,60882203,9,13,0.210136,2566.688522,2519.082764,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,539.353842,10722.737459,0.0
13140,61210000,61210000,0,0,1.000000,1585.380630,1471.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1585.380630,10722.737459,0.0

In [38]:
rgp = matrix_merge_df[matrix_merge_df["iris1"] == matrix_merge_df["iris2"]]
rgp = rgp[["iris1", "iris2", "type_iris", "pop_gp", "nb", "R", "swpop", "wpop", "pop_gp", "pop"]].copy()
rgp

,iris1,iris2,type_iris,pop_gp,nb,R,swpop,wpop,pop_gp,pop
0,10010000,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.000000
5,10020000,10020000,C,243.104024,0.0,0.0,2145.470352,243.104024,243.104024,267.000000
8,10040101,10040101,A,1634.474221,0.0,0.0,1634.474221,1634.474221,1634.474221,1796.951774
9,10040102,10040102,A,3620.863213,0.0,0.0,4111.975465,3620.863213,3620.863213,3837.421806
11,10040201,10040201,A,4121.595284,0.0,0.0,5748.703709,4121.595284,4121.595284,4393.228271
...,...,...,...,...,...,...,...,...,...,...
771463,2023560000,2023560000,C,187.551778,0.0,0.0,196.062448,187.551778,187.551778,148.000000
771467,2023610000,2023610000,C,291.459505,0.0,0.0,474.738489,291.459505,291.459505,306.000000
771469,2023640000,2023640000,C,44.591632,0.0,0.0,47.936296,44.591632,44.591632,36.000000
771472,2023650000,2023650000,C,120.798014,0.0,0.0,265.979710,120.798014,120.798014,100.000000
771473,2023660000,2023660000,C,127.766580,0.0,0.0,127.766580,127.766580,127.766580,108.000000

In [39]:
rgp[(rgp["iris1"]==debug) | (rgp["iris1"]==debug)].to_excel(writer, sheet_name=f"rgp", index=None)
rgp[(rgp["iris1"]==debug) | (rgp["iris1"]==debug)]

,iris1,iris2,type_iris,pop_gp,nb,R,swpop,wpop,pop_gp,pop
13140,61210000,61210000,C,1585.38063,0.0,0.0,10722.737459,1585.38063,1585.38063,1471.0

In [40]:
apl = matrix_merge_df.merge(rgp, on="iris2", suffixes=("", "_dest"))
apl

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest
0,10010000,10010000,0,0,1.000000,828.992958,832.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,828.992958,1876.269522,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.0
1,10280000,10010000,8,9,0.339596,828.992958,832.0,C,10280000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,281.522299,1539.630359,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.0
2,11880000,10010000,6,7,0.431711,828.992958,832.0,C,11880000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,357.884984,1903.058447,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.0
3,13510000,10010000,7,8,0.382893,828.992958,832.0,C,13510000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,317.415506,2208.156945,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.0
4,10010000,10280000,8,9,0.339596,597.452882,621.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,202.892326,1876.269522,0.0,10280000,C,597.452882,0.0,0.0,1539.630359,597.452882,597.452882,621.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771469,2023390000,2023390000,0,0,1.000000,40.612509,28.0,C,2023390000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,40.612509,40.612509,0.0,2023390000,C,40.612509,0.0,0.0,40.612509,40.612509,40.612509,28.0
771470,2023420000,2023420000,0,0,1.000000,2453.563310,2556.0,C,2023420000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2453.563310,2453.563310,0.0,2023420000,C,2453.563310,0.0,0.0,2453.563310,2453.563310,2453.563310,2556.0
771471,2023470000,2023470000,0,0,1.000000,336.603652,268.0,C,2023470000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,336.603652,336.603652,0.0,2023470000,C,336.603652,0.0,0.0,336.603652,336.603652,336.603652,268.0
771472,2023540000,2023540000,0,0,1.000000,478.663920,428.0,C,2023540000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,478.663920,478.663920,0.0,2023540000,C,478.663920,0.0,0.0,478.663920,478.663920,478.663920,428.0
771473,2023660000,2023660000,0,0,1.000000,127.766580,108.0,C,2023660000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,127.766580,127.766580,0.0,2023660000,C,127.766580,0.0,0.0,127.766580,127.766580,127.766580,108.0

In [41]:
apl[apl["iris"]==debug].to_excel(writer, sheet_name=f"join_iris1", index=None)
apl[apl["iris"]==debug]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest
12719,61210000,60880102,10,15,0.165299,1217.618689,1302.167160,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,201.271016,10722.737459,0.0,60880102,A,1217.618689,0.0,0.0,19297.732124,1217.618689,1217.618689,1302.167160
12870,61210000,60881601,9,14,0.186374,2087.063833,1963.668952,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,388.974385,10722.737459,0.0,60881601,A,2087.063833,0.0,0.0,14392.646602,2087.063833,2087.063833,1963.668952
12883,61210000,60881604,10,14,0.186374,3055.721245,2834.758352,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,569.506918,10722.737459,0.0,60881604,A,3055.721245,0.0,0.0,13072.819805,3055.721245,3055.721245,2834.758352
12927,61210000,60881701,9,13,0.210136,1641.948044,1708.308379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,345.032511,10722.737459,0.0,60881701,A,1641.948044,0.0,0.0,19270.885978,1641.948044,1641.948044,1708.308379
12944,61210000,60881702,9,13,0.210136,2095.417964,2060.393857,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,440.322898,10722.737459,0.0,60881702,A,2095.417964,0.0,0.0,17742.406415,2095.417964,2095.417964,2060.393857
12958,61210000,60881703,9,14,0.186374,1747.351193,1910.086974,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,325.660789,10722.737459,0.0,60881703,A,1747.351193,0.0,0.0,15284.396796,1747.351193,1747.351193,1910.086974
12974,61210000,60881704,9,14,0.186374,2155.294152,2157.701379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,401.690741,10722.737459,0.0,60881704,A,2155.294152,0.0,0.0,16665.470603,2155.294152,2155.294152,2157.701379
12990,61210000,60881705,9,13,0.210136,1888.443911,1878.223143,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,396.830184,10722.737459,0.0,60881705,A,1888.443911,0.0,0.0,15755.859626,1888.443911,1888.443911,1878.223143
13005,61210000,60882201,9,14,0.186374,1252.415053,1186.085985,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,233.417573,10722.737459,0.0,60882201,A,1252.415053,0.0,0.0,11261.777671,1252.415053,1252.415053,1186.085985
13021,61210000,60882202,9,14,0.186374,2226.745086,2234.919326,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,415.007335,10722.737459,0.0,60882202,A,2226.745086,0.0,0.0,15672.493971,2226.745086,2226.745086,2234.919326
13038,61210000,60882203,9,13,0.210136,2566.688522,2519.082764,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,539.353842,10722.737459,0.0,60882203,A,2566.688522,0.0,0.0,17517.000825,2566.688522,2566.688522,2519.082764
13087,61210000,60590000,11,15,0.165299,2346.881002,2189.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,387.936820,10722.737459,0.0,60590000,C,2346.881002,0.0,0.0,9277.573726,2346.881002,2346.881002,2189.000000
15533,61210000,60880509,8,14,0.186374,1601.504024,1758.198046,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,298.478673,10722.737459,0.0,60880509,A,1601.504024,0.0,0.0,11453.233524,1601.504024,1601.504024,1758.198046
15617,61210000,60880508,8,13,0.210136,2061.962146,2244.635592,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,433.292624,10722.737459,0.0,60880508,A,2061.962146,0.0,0.0,11330.512010,2061.962146,2061.962146,2244.635592
15767,61210000,61210000,0,0,1.000000,1585.380630,1471.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1585.380630,10722.737459,0.0,61210000,C,1585.380630,0.0,0.0,10722.737459,1585.380630,1585.380630,1471.000000
15929,61210000,60880601,9,15,0.165299,3211.497847,3400.367778,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,530.857024,10722.737459,0.0,60880601,A,3211.497847,0.0,0.0,10324.466624,3211.497847,3211.497847,3400.367778
16005,61210000,60881602,8,13,0.210136,2328.682642,2547.100345,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,489.340222,10722.737459,0.0,60881602,A,2328.682642,0.0,0.0,12236.125160,2328.682642,2328.682642,2547.100345
16017,61210000,60881603,9,15,0.165299,3267.105880,3334.828060,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,540.048970,10722.737459,0.0,60881603,A,3267.105880,0.0,0.0,11728.196494,3267.105880,3267.105880,3334.828060
16886,61210000,60880507,8,13,0.210136,3150.060094,3258.794977,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,661.941252,10722.737459,0.0,60880507,A,3150.060094,0.0,0.0,12195.078004,3150.060094,3150.060094,3258.794977
16939,61210000,60880602,9,14,0.186374,1515.075064,1564.628064,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,282.370564,10722.737459,0.0,60880602,A,1515.075064,0.0,0.0,7759.429044,1515.075064,1515.075064,1564.628064
16951,61210000,60880603,9,15,0.165299,2825.496170,2969.126397,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,467.051376,10722.737459,0.0,60880603,A,2825.496170,0.0,0.0,9209.675015,2825.496170,2825.496170,2969.126397
16961,61210000,60880604,9,15,0.165299,2503.716717,2776.024755,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,413.861590,10722.737459,0.0,60880604,A,2503.716717,0.0,0.0,9698.534965,2503.716717,2503.716717,2776.024755
16971,61210000,60880701,9,15,0.165299,2269.280377,2561.518621,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,375.109523,10722.737459,0.0,60880701,A,2269.280377,0.0,0.0,8485.361587,2269.280377,2269.280377,2561.518621

In [42]:
apl = apl.sort_values(by=['iris1', "iris2"])
apl["ap"] = apl["accessibilite_weight"] * apl["R_dest"]
apl.head(5)

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest,ap
0,10010000,10010000,0,0,1.000000,828.992958,832.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,828.992958,1876.269522,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.0,0.0
4,10010000,10280000,8,9,0.339596,597.452882,621.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,202.892326,1876.269522,0.0,10280000,C,597.452882,0.0,0.0,1539.630359,597.452882,597.452882,621.0,0.0
8,10010000,11880000,6,7,0.431711,626.194568,689.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,270.334785,1876.269522,0.0,11880000,C,626.194568,0.0,0.0,1903.058447,626.194568,626.194568,689.0,0.0
14,10010000,13510000,7,8,0.382893,1499.242934,1613.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,574.049454,1876.269522,0.0,13510000,C,1499.242934,0.0,0.0,2208.156945,1499.242934,1499.242934,1613.0,0.0
18,10020000,10020000,0,0,1.000000,243.104024,267.0,C,10020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,243.104024,2145.470352,0.0,10020000,C,243.104024,0.0,0.0,2145.470352,243.104024,243.104024,267.0,0.0

In [43]:
apl[apl["iris"]==debug].to_excel(writer, sheet_name=f"ap", index=None)
apl[apl["iris"]==debug]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest,ap
13087,61210000,60590000,11,15,0.165299,2346.881002,2189.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,387.936820,10722.737459,0.0,60590000,C,2346.881002,0.0,0.0,9277.573726,2346.881002,2346.881002,2189.000000,0.0
12719,61210000,60880102,10,15,0.165299,1217.618689,1302.167160,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,201.271016,10722.737459,0.0,60880102,A,1217.618689,0.0,0.0,19297.732124,1217.618689,1217.618689,1302.167160,0.0
16886,61210000,60880507,8,13,0.210136,3150.060094,3258.794977,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,661.941252,10722.737459,0.0,60880507,A,3150.060094,0.0,0.0,12195.078004,3150.060094,3150.060094,3258.794977,0.0
15617,61210000,60880508,8,13,0.210136,2061.962146,2244.635592,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,433.292624,10722.737459,0.0,60880508,A,2061.962146,0.0,0.0,11330.512010,2061.962146,2061.962146,2244.635592,0.0
15533,61210000,60880509,8,14,0.186374,1601.504024,1758.198046,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,298.478673,10722.737459,0.0,60880509,A,1601.504024,0.0,0.0,11453.233524,1601.504024,1601.504024,1758.198046,0.0
15929,61210000,60880601,9,15,0.165299,3211.497847,3400.367778,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,530.857024,10722.737459,0.0,60880601,A,3211.497847,0.0,0.0,10324.466624,3211.497847,3211.497847,3400.367778,0.0
16939,61210000,60880602,9,14,0.186374,1515.075064,1564.628064,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,282.370564,10722.737459,0.0,60880602,A,1515.075064,0.0,0.0,7759.429044,1515.075064,1515.075064,1564.628064,0.0
16951,61210000,60880603,9,15,0.165299,2825.496170,2969.126397,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,467.051376,10722.737459,0.0,60880603,A,2825.496170,0.0,0.0,9209.675015,2825.496170,2825.496170,2969.126397,0.0
16961,61210000,60880604,9,15,0.165299,2503.716717,2776.024755,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,413.861590,10722.737459,0.0,60880604,A,2503.716717,0.0,0.0,9698.534965,2503.716717,2503.716717,2776.024755,0.0
16971,61210000,60880701,9,15,0.165299,2269.280377,2561.518621,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,375.109523,10722.737459,0.0,60880701,A,2269.280377,0.0,0.0,8485.361587,2269.280377,2269.280377,2561.518621,0.0
12870,61210000,60881601,9,14,0.186374,2087.063833,1963.668952,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,388.974385,10722.737459,0.0,60881601,A,2087.063833,0.0,0.0,14392.646602,2087.063833,2087.063833,1963.668952,0.0
16005,61210000,60881602,8,13,0.210136,2328.682642,2547.100345,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,489.340222,10722.737459,0.0,60881602,A,2328.682642,0.0,0.0,12236.125160,2328.682642,2328.682642,2547.100345,0.0
16017,61210000,60881603,9,15,0.165299,3267.105880,3334.828060,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,540.048970,10722.737459,0.0,60881603,A,3267.105880,0.0,0.0,11728.196494,3267.105880,3267.105880,3334.828060,0.0
12883,61210000,60881604,10,14,0.186374,3055.721245,2834.758352,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,569.506918,10722.737459,0.0,60881604,A,3055.721245,0.0,0.0,13072.819805,3055.721245,3055.721245,2834.758352,0.0
12927,61210000,60881701,9,13,0.210136,1641.948044,1708.308379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,345.032511,10722.737459,0.0,60881701,A,1641.948044,0.0,0.0,19270.885978,1641.948044,1641.948044,1708.308379,0.0
12944,61210000,60881702,9,13,0.210136,2095.417964,2060.393857,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,440.322898,10722.737459,0.0,60881702,A,2095.417964,0.0,0.0,17742.406415,2095.417964,2095.417964,2060.393857,0.0
12958,61210000,60881703,9,14,0.186374,1747.351193,1910.086974,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,325.660789,10722.737459,0.0,60881703,A,1747.351193,0.0,0.0,15284.396796,1747.351193,1747.351193,1910.086974,0.0
12974,61210000,60881704,9,14,0.186374,2155.294152,2157.701379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,401.690741,10722.737459,0.0,60881704,A,2155.294152,0.0,0.0,16665.470603,2155.294152,2155.294152,2157.701379,0.0
12990,61210000,60881705,9,13,0.210136,1888.443911,1878.223143,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,396.830184,10722.737459,0.0,60881705,A,1888.443911,0.0,0.0,15755.859626,1888.443911,1888.443911,1878.223143,0.0
13005,61210000,60882201,9,14,0.186374,1252.415053,1186.085985,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,233.417573,10722.737459,0.0,60882201,A,1252.415053,0.0,0.0,11261.777671,1252.415053,1252.415053,1186.085985,0.0
13021,61210000,60882202,9,14,0.186374,2226.745086,2234.919326,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,415.007335,10722.737459,0.0,60882202,A,2226.745086,0.0,0.0,15672.493971,2226.745086,2226.745086,2234.919326,0.0
13038,61210000,60882203,9,13,0.210136,2566.688522,2519.082764,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,539.353842,10722.737459,0.0,60882203,A,2566.688522,0.0,0.0,17517.000825,2566.688522,2566.688522,2519.082764,0.0
15767,61210000,61210000,0,0,1.000000,1585.380630,1471.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1585.380630,10722.737459,0.0,61210000,C,1585.380630,0.0,0.0,10722.737459,1585.380630,1585.380630,1471.000000,0.0

In [44]:
apl["apl"] = apl.groupby("iris1")["ap"].transform("sum")
apl

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest,ap,apl
0,10010000,10010000,0,0,1.000000,828.992958,832.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,828.992958,1876.269522,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.0,0.0,0.0
4,10010000,10280000,8,9,0.339596,597.452882,621.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,202.892326,1876.269522,0.0,10280000,C,597.452882,0.0,0.0,1539.630359,597.452882,597.452882,621.0,0.0,0.0
8,10010000,11880000,6,7,0.431711,626.194568,689.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,270.334785,1876.269522,0.0,11880000,C,626.194568,0.0,0.0,1903.058447,626.194568,626.194568,689.0,0.0,0.0
14,10010000,13510000,7,8,0.382893,1499.242934,1613.0,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,574.049454,1876.269522,0.0,13510000,C,1499.242934,0.0,0.0,2208.156945,1499.242934,1499.242934,1613.0,0.0,0.0
18,10020000,10020000,0,0,1.000000,243.104024,267.0,C,10020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,243.104024,2145.470352,0.0,10020000,C,243.104024,0.0,0.0,2145.470352,243.104024,243.104024,267.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
770787,2023640000,2022920000,11,26,0.044157,75.744545,61.0,C,2023640000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3.344665,47.936296,0.0,2022920000,C,75.744545,0.0,0.0,88.301898,75.744545,75.744545,61.0,0.0,0.0
771445,2023640000,2023640000,0,0,1.000000,44.591632,36.0,C,2023640000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,44.591632,47.936296,0.0,2023640000,C,44.591632,0.0,0.0,47.936296,44.591632,44.591632,36.0,0.0,0.0
771261,2023650000,2021350000,6,8,0.382893,379.170525,324.0,C,2023650000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,145.181697,265.979710,0.0,2021350000,C,379.170525,0.0,0.0,425.423225,379.170525,379.170525,324.0,0.0,0.0
771263,2023650000,2023650000,0,0,1.000000,120.798014,100.0,C,2023650000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,120.798014,265.979710,0.0,2023650000,C,120.798014,0.0,0.0,265.979710,120.798014,120.798014,100.0,0.0,0.0
771473,2023660000,2023660000,0,0,1.000000,127.766580,108.0,C,2023660000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,127.766580,127.766580,0.0,2023660000,C,127.766580,0.0,0.0,127.766580,127.766580,127.766580,108.0,0.0,0.0

In [45]:
apl[apl["iris"]==debug].to_excel(writer, sheet_name=f"sum_ap", index=None)
apl[apl["iris"]==debug]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest,ap,apl
13087,61210000,60590000,11,15,0.165299,2346.881002,2189.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,387.936820,10722.737459,0.0,60590000,C,2346.881002,0.0,0.0,9277.573726,2346.881002,2346.881002,2189.000000,0.0,0.0
12719,61210000,60880102,10,15,0.165299,1217.618689,1302.167160,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,201.271016,10722.737459,0.0,60880102,A,1217.618689,0.0,0.0,19297.732124,1217.618689,1217.618689,1302.167160,0.0,0.0
16886,61210000,60880507,8,13,0.210136,3150.060094,3258.794977,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,661.941252,10722.737459,0.0,60880507,A,3150.060094,0.0,0.0,12195.078004,3150.060094,3150.060094,3258.794977,0.0,0.0
15617,61210000,60880508,8,13,0.210136,2061.962146,2244.635592,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,433.292624,10722.737459,0.0,60880508,A,2061.962146,0.0,0.0,11330.512010,2061.962146,2061.962146,2244.635592,0.0,0.0
15533,61210000,60880509,8,14,0.186374,1601.504024,1758.198046,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,298.478673,10722.737459,0.0,60880509,A,1601.504024,0.0,0.0,11453.233524,1601.504024,1601.504024,1758.198046,0.0,0.0
15929,61210000,60880601,9,15,0.165299,3211.497847,3400.367778,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,530.857024,10722.737459,0.0,60880601,A,3211.497847,0.0,0.0,10324.466624,3211.497847,3211.497847,3400.367778,0.0,0.0
16939,61210000,60880602,9,14,0.186374,1515.075064,1564.628064,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,282.370564,10722.737459,0.0,60880602,A,1515.075064,0.0,0.0,7759.429044,1515.075064,1515.075064,1564.628064,0.0,0.0
16951,61210000,60880603,9,15,0.165299,2825.496170,2969.126397,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,467.051376,10722.737459,0.0,60880603,A,2825.496170,0.0,0.0,9209.675015,2825.496170,2825.496170,2969.126397,0.0,0.0
16961,61210000,60880604,9,15,0.165299,2503.716717,2776.024755,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,413.861590,10722.737459,0.0,60880604,A,2503.716717,0.0,0.0,9698.534965,2503.716717,2503.716717,2776.024755,0.0,0.0
16971,61210000,60880701,9,15,0.165299,2269.280377,2561.518621,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,375.109523,10722.737459,0.0,60880701,A,2269.280377,0.0,0.0,8485.361587,2269.280377,2269.280377,2561.518621,0.0,0.0
12870,61210000,60881601,9,14,0.186374,2087.063833,1963.668952,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,388.974385,10722.737459,0.0,60881601,A,2087.063833,0.0,0.0,14392.646602,2087.063833,2087.063833,1963.668952,0.0,0.0
16005,61210000,60881602,8,13,0.210136,2328.682642,2547.100345,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,489.340222,10722.737459,0.0,60881602,A,2328.682642,0.0,0.0,12236.125160,2328.682642,2328.682642,2547.100345,0.0,0.0
16017,61210000,60881603,9,15,0.165299,3267.105880,3334.828060,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,540.048970,10722.737459,0.0,60881603,A,3267.105880,0.0,0.0,11728.196494,3267.105880,3267.105880,3334.828060,0.0,0.0
12883,61210000,60881604,10,14,0.186374,3055.721245,2834.758352,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,569.506918,10722.737459,0.0,60881604,A,3055.721245,0.0,0.0,13072.819805,3055.721245,3055.721245,2834.758352,0.0,0.0
12927,61210000,60881701,9,13,0.210136,1641.948044,1708.308379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,345.032511,10722.737459,0.0,60881701,A,1641.948044,0.0,0.0,19270.885978,1641.948044,1641.948044,1708.308379,0.0,0.0
12944,61210000,60881702,9,13,0.210136,2095.417964,2060.393857,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,440.322898,10722.737459,0.0,60881702,A,2095.417964,0.0,0.0,17742.406415,2095.417964,2095.417964,2060.393857,0.0,0.0
12958,61210000,60881703,9,14,0.186374,1747.351193,1910.086974,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,325.660789,10722.737459,0.0,60881703,A,1747.351193,0.0,0.0,15284.396796,1747.351193,1747.351193,1910.086974,0.0,0.0
12974,61210000,60881704,9,14,0.186374,2155.294152,2157.701379,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,401.690741,10722.737459,0.0,60881704,A,2155.294152,0.0,0.0,16665.470603,2155.294152,2155.294152,2157.701379,0.0,0.0
12990,61210000,60881705,9,13,0.210136,1888.443911,1878.223143,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,396.830184,10722.737459,0.0,60881705,A,1888.443911,0.0,0.0,15755.859626,1888.443911,1888.443911,1878.223143,0.0,0.0
13005,61210000,60882201,9,14,0.186374,1252.415053,1186.085985,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,233.417573,10722.737459,0.0,60882201,A,1252.415053,0.0,0.0,11261.777671,1252.415053,1252.415053,1186.085985,0.0,0.0
13021,61210000,60882202,9,14,0.186374,2226.745086,2234.919326,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,415.007335,10722.737459,0.0,60882202,A,2226.745086,0.0,0.0,15672.493971,2226.745086,2226.745086,2234.919326,0.0,0.0
13038,61210000,60882203,9,13,0.210136,2566.688522,2519.082764,A,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,539.353842,10722.737459,0.0,60882203,A,2566.688522,0.0,0.0,17517.000825,2566.688522,2566.688522,2519.082764,0.0,0.0
15767,61210000,61210000,0,0,1.000000,1585.380630,1471.000000,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1585.380630,10722.737459,0.0,61210000,C,1585.380630,0.0,0.0,10722.737459,1585.380630,1585.380630,1471.000000,0.0,0.0

In [46]:
apl2 = apl[apl["iris1"] == apl["iris2"]]
apl2

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest,ap,apl
0,10010000,10010000,0,0,1.0,828.992958,832.000000,C,10010000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,828.992958,1876.269522,0.0,10010000,C,828.992958,0.0,0.0,1876.269522,828.992958,828.992958,832.000000,0.0,0.0
18,10020000,10020000,0,0,1.0,243.104024,267.000000,C,10020000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,243.104024,2145.470352,0.0,10020000,C,243.104024,0.0,0.0,2145.470352,243.104024,243.104024,267.000000,0.0,0.0
38,10040101,10040101,0,0,1.0,1634.474221,1796.951774,A,10040101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1634.474221,1634.474221,0.0,10040101,A,1634.474221,0.0,0.0,1634.474221,1634.474221,1634.474221,1796.951774,0.0,0.0
39,10040102,10040102,0,0,1.0,3620.863213,3837.421806,A,10040102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,3620.863213,4111.975465,0.0,10040102,A,3620.863213,0.0,0.0,4111.975465,3620.863213,3620.863213,3837.421806,0.0,0.0
48,10040201,10040201,0,0,1.0,4121.595284,4393.228271,A,10040201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,4121.595284,5748.703709,0.0,10040201,A,4121.595284,0.0,0.0,5748.703709,4121.595284,4121.595284,4393.228271,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
771399,2023560000,2023560000,0,0,1.0,187.551778,148.000000,C,2023560000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,187.551778,196.062448,0.0,2023560000,C,187.551778,0.0,0.0,196.062448,187.551778,187.551778,148.000000,0.0,0.0
770818,2023610000,2023610000,0,0,1.0,291.459505,306.000000,C,2023610000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,291.459505,474.738489,0.0,2023610000,C,291.459505,0.0,0.0,474.738489,291.459505,291.459505,306.000000,0.0,0.0
771445,2023640000,2023640000,0,0,1.0,44.591632,36.000000,C,2023640000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,44.591632,47.936296,0.0,2023640000,C,44.591632,0.0,0.0,47.936296,44.591632,44.591632,36.000000,0.0,0.0
771263,2023650000,2023650000,0,0,1.0,120.798014,100.000000,C,2023650000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,120.798014,265.979710,0.0,2023650000,C,120.798014,0.0,0.0,265.979710,120.798014,120.798014,100.000000,0.0,0.0
771473,2023660000,2023660000,0,0,1.0,127.766580,108.000000,C,2023660000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,127.766580,127.766580,0.0,2023660000,C,127.766580,0.0,0.0,127.766580,127.766580,127.766580,108.000000,0.0,0.0

In [47]:
apl2[apl2["iris"]==debug].to_excel(writer, sheet_name=f"apl", index=None)
writer.close()
apl2[apl2["iris"]==debug]

,iris1,iris2,km,time,accessibilite_weight,pop_gp,pop,type_iris,iris,id,inpp,nom,prenom,dept_id,adresse_norm_id,lon,lat,code_mode_exercice,key,nb_cabinet,weight,nb,wpop,swpop,R,iris1_dest,type_iris_dest,pop_gp_dest,nb_dest,R_dest,swpop_dest,wpop_dest,pop_gp_dest,pop_dest,ap,apl
15767,61210000,61210000,0,0,1.0,1585.38063,1471.0,C,61210000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1585.38063,10722.737459,0.0,61210000,C,1585.38063,0.0,0.0,10722.737459,1585.38063,1585.38063,1471.0,0.0,0.0

In [48]:
print(year, specialite, source)
apl2["apl"].describe()
# 21-10-PA:67-57 avec ratio:68-58
# 20-10-PA:68-58 avec ratio:69-59

21 10 PA

count    48569.0
mean         0.0
std          0.0
min          0.0
25%          0.0
50%          0.0
75%          0.0
max          0.0
Name: apl, dtype: float64

In [49]:
# 21 10 PA
# count    48569.000000
# mean        66.239008
# std         36.200523
# min          0.000000
# 25%         40.432111
# 50%         56.872725
# 75%         85.083597
# max        681.212229

# 23 10 PA
# count    48569.000000
# mean        67.704332
# std         37.706173
# min          0.000000
# 25%         40.971273
# 50%         57.986870
# 75%         86.747319
# max        671.098376

# Avec prise en compte des cabinets non L
# 23 10 PA
# count    48569.000000
# mean        64.104830
# std         35.929837
# min          0.000000
# 25%         38.716316
# 50%         55.025585
# 75%         82.063870
# max        671.098376

# 24 10 PA
# count    48569.000000
# mean        62.960575
# std         36.148895
# min          0.000000
# 25%         37.356832
# 50%         53.792301
# 75%         80.853780
# max        671.109886

# 25 10 PA
# count    48569.000000
# mean        63.364476
# std         36.585777
# min          0.000000
# 25%         37.419434
# 50%         53.987877
# 75%         81.566145
# max        671.109886

In [50]:
dico = {"year":year, "specialite_id":specialite, "source":source, "time":time, "time_type":time_type, "exp":accessibilite_exp}
dico["mean"] = np.mean(apl2["apl"])
dico["std"] = np.std(apl2["apl"])
dico["q10"], dico["q25"], dico["q50"], dico["q75"], dico["q90"] = np.quantile(apl2["apl"], [0.1, 0.25, 0.5, 0.75, 0.9])
dico["min"] = np.min(apl2["apl"])
dico["max"] = np.max(apl2["apl"])
dico["date"] = datetime.datetime.now()
dico["key"] = random.randint(0, 1000000000000)
dico

{'year': 21,
 'specialite_id': 10,
 'source': 'PA',
 'time': 30,
 'time_type': 'HC',
 'exp': -0.12,
 'mean': 0.0,
 'std': 0.0,
 'q10': 0.0,
 'q25': 0.0,
 'q50': 0.0,
 'q75': 0.0,
 'q90': 0.0,
 'min': 0.0,
 'max': 0.0,
 'date': datetime.datetime(2026, 5, 25, 13, 26, 25, 986453),
 'key': 676281624172}

In [51]:
study = pd.DataFrame(dico, index=[dico["key"]])
study

,year,specialite_id,source,time,time_type,exp,mean,std,q10,q25,q50,q75,q90,min,max,date,key
676281624172,21,10,PA,30,HC,-0.12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2026-05-25 13:26:25.986453,676281624172

In [52]:
apl3 = apl2[["iris1", "type_iris", "nb", "apl", "ap", "accessibilite_weight", "wpop", "swpop", "R", "pop_gp","pop"]]
apl3 = apl3.rename(columns={'iris1': 'iris'})
apl3.head(5)

,iris,type_iris,nb,apl,ap,accessibilite_weight,wpop,swpop,R,pop_gp,pop
0,10010000,C,0.0,0.0,0.0,1.0,828.992958,1876.269522,0.0,828.992958,832.000000
18,10020000,C,0.0,0.0,0.0,1.0,243.104024,2145.470352,0.0,243.104024,267.000000
38,10040101,A,0.0,0.0,0.0,1.0,1634.474221,1634.474221,0.0,1634.474221,1796.951774
39,10040102,A,0.0,0.0,0.0,1.0,3620.863213,4111.975465,0.0,3620.863213,3837.421806
48,10040201,A,0.0,0.0,0.0,1.0,4121.595284,5748.703709,0.0,4121.595284,4393.228271

In [53]:
apl3[apl3["iris"]==61070000]

,iris,type_iris,nb,apl,ap,accessibilite_weight,wpop,swpop,R,pop_gp,pop
15520,61070000,C,0.0,0.0,0.0,1.0,75.119922,165.469252,0.0,75.119922,65.0

In [54]:
def get_iriss():
    sql = f"""
select i.id "iris", i.code "iris_string", i.nom "iris_label", c.dept_id "dept", c.code "code_commune", c.nom "commune_label", 20{year} "year", {specialite} "specialite" from iris.iris i
join iris.commune c on c.id=i.commune_id
"""
    print(sql)
    return pd.read_sql(text(sql), config.connection_string)

iriss = get_iriss()
iriss

select i.id "iris", i.code "iris_string", i.nom "iris_label", c.dept_id "dept", c.code "code_commune", c.nom "commune_label", 2021 "year", 10 "specialite" from iris.iris i
join iris.commune c on c.id=i.commune_id

,iris,iris_string,iris_label,dept,code_commune,commune_label,year,specialite
0,821300000,821300000,Montjoi,82,82130,Montjoi,2021,10
1,811540000,811540000,Marnaves,81,81154,Marnaves,2021,10
2,840060000,840060000,Auribeau,84,84006,Auribeau,2021,10
3,821570000,821570000,Saint-Beauzeil,82,82157,Saint-Beauzeil,2021,10
4,840880101,840880101,Secteur Ouest,84,84088,Pernes-les-Fontaines,2021,10
...,...,...,...,...,...,...,...,...
48564,912280114,912280114,Mousseau-Bonhomme en Pierre,91,91228,Évry-Courcouronnes,2021,10
48565,912280204,912280204,Courcouronnes Centre Nord,91,91228,Évry-Courcouronnes,2021,10
48566,920460108,920460108,Les Sablonnières,92,92046,Malakoff,2021,10
48567,940460202,940460202,Alfort 2,94,94046,Maisons-Alfort,2021,10
48568,940540104,940540104,Tilleuls,94,94054,Orly,2021,10

In [55]:
apl_final = apl3.merge(iriss, on="iris", how="left", suffixes=("", "_dest"))
apl_final = apl_final[["year", "specialite", "iris", "iris_string", "type_iris", "nb", "apl", "ap", "accessibilite_weight", "R", "wpop", "swpop", "pop_gp","pop", "iris_label", "dept", "code_commune", "commune_label"]]
apl_final["year"]=year
apl_final

,year,specialite,iris,iris_string,type_iris,nb,apl,ap,accessibilite_weight,R,wpop,swpop,pop_gp,pop,iris_label,dept,code_commune,commune_label
0,21,10,10010000,010010000,C,0.0,0.0,0.0,1.0,0.0,828.992958,1876.269522,828.992958,832.000000,L'Abergement-Clémenciat,1,01001,L'Abergement-Clémenciat
1,21,10,10020000,010020000,C,0.0,0.0,0.0,1.0,0.0,243.104024,2145.470352,243.104024,267.000000,L'Abergement-de-Varey,1,01002,L'Abergement-de-Varey
2,21,10,10040101,010040101,A,0.0,0.0,0.0,1.0,0.0,1634.474221,1634.474221,1634.474221,1796.951774,Les Pérouses-Triangle d'Activités,1,01004,Ambérieu-en-Bugey
3,21,10,10040102,010040102,A,0.0,0.0,0.0,1.0,0.0,3620.863213,4111.975465,3620.863213,3837.421806,Longeray-Gare,1,01004,Ambérieu-en-Bugey
4,21,10,10040201,010040201,A,0.0,0.0,0.0,1.0,0.0,4121.595284,5748.703709,4121.595284,4393.228271,Centre-Saint-Germain-Vareilles,1,01004,Ambérieu-en-Bugey
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48564,21,10,2023560000,2B3560000,C,0.0,0.0,0.0,1.0,0.0,187.551778,196.062448,187.551778,148.000000,Zalana,202,2B356,Zalana
48565,21,10,2023610000,2B3610000,C,0.0,0.0,0.0,1.0,0.0,291.459505,474.738489,291.459505,306.000000,Zilia,202,2B361,Zilia
48566,21,10,2023640000,2B3640000,C,0.0,0.0,0.0,1.0,0.0,44.591632,47.936296,44.591632,36.000000,Zuani,202,2B364,Zuani
48567,21,10,2023650000,2B3650000,C,0.0,0.0,0.0,1.0,0.0,120.798014,265.979710,120.798014,100.000000,San-Gavino-di-Fiumorbo,202,2B365,San-Gavino-di-Fiumorbo
48568,21,10,2023660000,2B3660000,C,0.0,0.0,0.0,1.0,0.0,127.766580,127.766580,127.766580,108.000000,Chisa,202,2B366,Chisa

In [56]:
apl_final[apl_final["iris_string"]=="061070000"]

,year,specialite,iris,iris_string,type_iris,nb,apl,ap,accessibilite_weight,R,wpop,swpop,pop_gp,pop,iris_label,dept,code_commune,commune_label
2499,21,10,61070000,061070000,C,0.0,0.0,0.0,1.0,0.0,75.119922,165.469252,75.119922,65.0,La Roque-en-Provence,6,06107,La Roque-en-Provence

In [57]:
d6=apl_final[apl_final["dept"]==6]
d6

,year,specialite,iris,iris_string,type_iris,nb,apl,ap,accessibilite_weight,R,wpop,swpop,pop_gp,pop,iris_label,dept,code_commune,commune_label
2095,21,10,60010000,060010000,C,0.0,0.0,0.0,1.0,0.0,102.897772,102.897772,102.897772,93.000000,Aiglun,6,06001,Aiglun
2096,21,10,60020000,060020000,C,0.0,0.0,0.0,1.0,0.0,65.256932,85.781674,65.256932,51.000000,Amirat,6,06002,Amirat
2097,21,10,60030000,060030000,C,0.0,0.0,0.0,1.0,0.0,687.327185,869.444256,687.327185,640.000000,Andon,6,06003,Andon
2098,21,10,60040101,060040101,C,0.0,0.0,0.0,1.0,0.0,1789.616425,10224.949577,1789.616425,1763.364267,Les Trois Moulins,6,06004,Antibes
2099,21,10,60040102,060040102,A,0.0,0.0,0.0,1.0,0.0,2464.955725,13625.774761,2464.955725,2534.265666,Les Semboules,6,06004,Antibes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2590,21,10,61610105,061610105,A,0.0,0.0,0.0,1.0,0.0,3605.428239,13948.590642,3605.428239,3584.453834,Marina,6,06161,Villeneuve-Loubet
2591,21,10,61610106,061610106,A,0.0,0.0,0.0,1.0,0.0,3577.951110,14402.586187,3577.951110,3539.143531,Vaugrenier,6,06161,Villeneuve-Loubet
2592,21,10,61610107,061610107,A,0.0,0.0,0.0,1.0,0.0,2665.817551,15851.378098,2665.817551,2766.654836,Plan,6,06161,Villeneuve-Loubet
2593,21,10,61620000,061620000,C,0.0,0.0,0.0,1.0,0.0,797.762765,797.762765,797.762765,719.000000,La Brigue,6,06162,La Brigue
2594,21,10,61630000,061630000,C,0.0,0.0,0.0,1.0,0.0,2218.292364,2218.292364,2218.292364,2021.000000,Tende,6,06163,Tende

In [58]:
d6["apl"].describe()
# Ca change à cause des cabinets multi-dept

count    500.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0
Name: apl, dtype: float64

In [59]:
# apl_final.to_csv("apl_france.csv", index=False)

In [60]:
# apl_final["study_key"]=dico["key"]
# study.to_sql("apl_study", config.connection_string, schema="apl", if_exists="append", index=False)
# apl_final.to_sql("apl", config.connection_string, schema="apl", if_exists="append", index=False)

In [61]:
sum_pop = np.sum(apl_final["pop_gp"])
apl_final["meanw"]=apl_final["apl"]*apl_final["pop_gp"]*len(apl_final)/sum_pop
np.mean(apl_final["meanw"])

0.0